data-pipeline/environment.yaml
data-pipeline/src/etl/convert.py
data-pipeline/src/etl/downloader.py
data-pipeline/src/etl/merge.py
data-pipeline/src/etl/runner.py
data-pipeline/src/etl/sources/census_acs_5year/constants.py
data-pipeline/src/etl/sources/census_acs_5year/etl.py
data-pipeline/src/main.py

Downloads and processes 'Age and Sex', 'ACS Demographic and Housing Estimates', 'Educational Attainment', and 'Household Size by Vehicles Available'.
Example output:
```json
{
"GEOID": "T45045000100",
"NAME": "Census Tract 1, Greenville County, South Carolina",
"YEAR": "2015-2019",
"educational_attainment__associate_degree": 70,
"educational_attainment__bachelor_degree": 377,
"educational_attainment__graduate_or_professional_degree": 324,
"educational_attainment__high_school_graduate_or_equivalent": 376,
"educational_attainment__no_high_school": 71,
"educational_attainment__some_college": 250,
"educational_attainment__some_high_school": 355,
"households__1_vehicle": 341,
"households__2_vehicles": 211,
"households__3_vehicles": 49,
"households__4_plus_vehicles": 21, …
```

feat(pipeline): add census acs 5-year estimates etl

---

frontend/index.html
frontend/src/App.tsx
frontend/src/components/layout/CoreFrame/CoreFrame.tsx
frontend/src/components/layout/CoreFrame/CoreFrameContext.ts
frontend/src/components/layout/CoreFrame/SidebarWrapper.tsx
frontend/src/components/layout/index.ts
frontend/src/components/navigation/AppNavigation.tsx
frontend/src/components/navigation/constants.ts
frontend/src/components/navigation/index.ts
frontend/src/views/EssentialServicesAccess.tsx
frontend/src/views/FutureOpportunities.tsx
frontend/src/views/GeneralAccess.tsx
frontend/src/views/JobAccess.tsx
frontend/src/views/RoadsVsTransit.tsx
frontend/src/views/index.ts

This PR adds a view for each tab of the dashboard. Views are located in the frontend/src/views folder.
Each view is initialized with an empty `CoreFrame` component. Each also includes the `AppNavigation` component, which provides the tabs for the dashboard.

feat(frontend): add views for each tab of the dashboard

---

frontend/beforeStart.js
frontend/src/App.tsx
frontend/src/components/common/SidebarContent/SidebarContent.tsx
frontend/src/components/common/index.ts
frontend/src/components/layout/CoreFrame/SidebarWrapper.tsx
frontend/src/components/options/areas/SelectedArea.tsx
frontend/src/components/options/areas/SelectedComparisonAreas.tsx
frontend/src/components/options/areas/index.ts
frontend/src/components/options/areas/useSelectedAreasState.tsx
frontend/src/components/options/compare/ComparisonModeSwitch.tsx
frontend/src/components/options/compare/index.ts
frontend/src/components/options/compare/useComparisonModeState.tsx
frontend/src/components/options/index.ts
frontend/src/components/options/seasons/SelectedComparisonSeasons.tsx
frontend/src/components/options/seasons/SelectedSeason.tsx
frontend/src/components/options/seasons/index.ts
frontend/src/components/options/seasons/useSelectedSeasonsState.ts
frontend/src/hooks/useAppData.ts
frontend/src/views/GeneralAccess.tsx

This PR adds a picker for the areas and seasons to the general access sidebar. It allows picking a single area or season. If the comparion mode checkbox is checked, it shows a `<select multiple />` for the areas and seasons, allowing more than one area and season to be selected. State is stored in the URL.
Equivalent URL: `http://localhost:5173/#/?areas=Brutontown%2CWest+End&seasons=Q4%3A2024%2CQ2%3A2021%2CQ4%3A2021&compare=1`
The checkboxes and selects are using the browser styles. We will probably change these to our own styles later.

feat(frontend): add areas and seasons picker to the general access sidebar

---

frontend/src/components/options/areas/SelectedArea.tsx
frontend/src/components/options/seasons/SelectedSeason.tsx

Previously, the <select> elements showed the first value in the options even though it was not selected. Now, when no option is selected, an empty option is inserted in front of the other options so that the dropdown shows that as the selection. The empty option goes away once a value is actually selected.
In the future, we will have the app set a defauly value in the URL (defaults TBD).

fix(frontend): show blank selections for area and season when there is no selection

---

.github/actions/prepare-pipeline-test/action.yaml
.github/actions/prepare-pipeline-test/run.sh
.github/workflows/data-pipeline-test.yaml
data-pipeline/environment.yaml
data-pipeline/src/etl/sources/replica/etl.py
data-pipeline/src/etl/sources/replica/transformers/count_segment_frequency.py
data-pipeline/src/etl/sources/replica/transformers/trips_as_lines.py
data-pipeline/src/main.py

This change affects the trips and network segments datasets.
Instead of storing trips layers as two separate layers based on the starting and ending points (and then merging them later after filtering by geogrpahic location), we now find all matching network segments from each trip and set the trip geography to be a multilinestring of the trip route. To ensure that the start and end point are preserved, they are respectively encoded as an extremely short line (1e-9) at the start and end of the multilinestring.
When forming the network segments layer, we now provide separate layers for each trip day (thursday or saturday). Instead of showing all possible network segments, the layer now only shows the segments that were actually used. Each segment also has an attribute for frequency (how …

feat(pipeline/replica): store trips as lines from network segments and derive network segments layer from trips

---

.github/workflows/data-pipeline-test.yaml
data-pipeline/src/etl/sources/replica/etl.py
data-pipeline/src/etl/sources/replica/runner.py
frontend/src/data.d.ts

There are now totals for non-public transit trips that could have used public transit. These are determined by checking if the entire trip fits within a walking or biking service area, which is generated from the greenlink_gtfs ETL.

feat(pipeline/replica): add statistics for possible conversions to public transit

---

data-pipeline/src/etl/sources/census_acs_5year/constants.py
data-pipeline/src/etl/sources/census_acs_5year/runner.py
data-pipeline/src/etl/sources/census_acs_5year/tract_etl.py

Downloads census tract shapes and matches them with area files to assign tract IDs.

feat(pipeline/census_acs_5year): add `areas` property to `time_series.json` with the area names that correspond to the associated tract

---

data-pipeline/src/etl/geodesic.py
data-pipeline/src/etl/sources/greenlink_gtfs/etl.py
data-pipeline/src/etl/sources/greenlink_gtfs/runner.py
data-pipeline/src/etl/sources/replica/process_etl.py
frontend/src/data.d.ts
frontend/src/hooks/useAppData.ts
frontend/src/utils/generateHash.ts
frontend/src/utils/index.ts
frontend/src/views/GeneralAccess.tsx

Statistics are calculated for the full service area. Statistics are also calculated for each area in input/replica_interest_area_polygons. The output is a JSON file at data/greenlink_gtfs/service_coverage_stats.json
The data in the JSON file are shown on the dashboard on tab 1.
Statistics are included in the synthentic demographics JSON that is already generated by the replica ETL. It follows this structure:
```
households?: number;
population?: number;
households_in_service_areas?: { walk: number; bike: number };
population_in_service_areas?: { walk: number; bike: number };
```

feat: add service coverge statistics

---

frontend/src/hooks/useAppData.ts
frontend/src/views/GeneralAccess.tsx

feat(frontend): show boardings and alightings service statistics

---

.github/workflows/data-pipeline-test.yaml
data-pipeline/src/etl/sources/geocoder/etl.py
data-pipeline/src/etl/sources/geocoder/runner.py

This module processes CSV files containing address data and geocodes them using a two-tier approach:
Requirements:
- Input CSV files must contain either:
- Address + ZIP Code columns, OR
- Street + Zip columns
Files should be placed in ./input/to_geocode/ directory
Geocoding Process:
1. Primary: ArcGIS GeocodeServer (local Greenville service)
2. Fallback: Nominatim OpenStreetMap (for failed addresses)
The geocoder uses the Address/Street field as the primary street address and the ZIP Code/Zip field as the postal code for geocoding requests. Both fields are sent to the ArcGIS service, with Nominatim fallback using a combined query string of both fields.
Outputs:
1. geocoded_[filename].geojson - Successfully geocoded addresses with geometry
2. failed_[filename].csv - Addresses that both …

feat(pipeline): add geocoder

---

.github/workflows/data-pipeline-test.yaml
data-pipeline/src/etl/geodesic.py
data-pipeline/src/etl/sources/essential_services/etl.py
data-pipeline/src/etl/sources/essential_services/runner.py
data-pipeline/src/etl/sources/geocoder/etl.py
frontend/package.json
frontend/src/App.tsx
frontend/src/components/common/Select/SelectOne.tsx
frontend/src/components/options/areas/SelectedArea.tsx
frontend/src/components/options/seasons/SelectedSeason.tsx
frontend/src/data.d.ts
frontend/src/hooks/useAppData.ts
frontend/src/hooks/useMapData.tsx
frontend/src/views/EssentialServicesAccess.tsx
frontend/src/views/GeneralAccess.tsx
frontend/src/views/RoadsVsTransit.tsx
frontend/tsconfig.app.json

This PR adds the following essential services data:
- percent access to healthcare via public transit
- percent access to grocery stores via public transit
- percent access to child care centers via public transit
- percent access to commercial zones
- measured mean travel time to healthcare locations
- measured mean travel time to grocery stores
- measured mean travel time to child care centers
- measured mean travel time to commercial zones
Healthcare data, grocery store data, and child care center data are read from the output of the geocoder etl. They should be provided to the goeocder in the `input/to_geocode` folder with the following name formats:
| Dataset | File name |
| --- | --- |
| healthcare | healthcare__YYYY-MM-DD |
| childcare | childcare__YYYY-MM-DD |
| grocery stores | …

feat: add essential services data

---

frontend/package-lock.json
frontend/package.json
frontend/src/components/common/Section/SectionEntry.tsx
frontend/src/components/common/Statistic/Figure.tsx
frontend/src/components/common/Statistic/index.ts
frontend/src/components/common/Statistic/plot/PlotContainer.tsx
frontend/src/components/common/Statistic/plot/presets/facetedHorizontalBar.ts
frontend/src/components/common/Statistic/plot/presets/hoizontalBar.ts
frontend/src/components/common/index.ts
frontend/src/index.d.ts
frontend/src/utils/index.ts
frontend/src/utils/toTidyNominal.ts

This PR adds an addition component to sthe statisitics componets for figures.
With `Statistic.Figure`, you can now render a plot by specifying a plotcon fig. It is wrapped in the same style container as the other statistics components.
Plots can be directly rendered with `PlotContainer` as well.
Example:

feat(frontend): add `Figure` statistic component

---

data-pipeline/src/etl/sources/census_acs_5year/tract_etl.py
frontend/src/data.d.ts
frontend/src/hooks/useAppData.ts
frontend/src/views/GeneralAccess.tsx

- Tracts are now matched to areas based on tract centroid intersection with areas. Before, they were mistakenly matched by polygon intersection.
- The census data only fetched once per page load.
- The census data is filtered by area and year before being returned for a season-area's data object.
- The population estimate for area demographics now shows the sum of population of all intersecting tracts.
- The households without a vehicle (ACS) section now shows the sum of households without vehicles of all intersecting tracts.
Bug fix:
- Trips that could use public transit now shows the percetange value instead of showing the fraction value.

feat: show remaining census data on tab 1 (general access)

---

data-pipeline/src/etl/sources/passthrough/runner.py

It simply copies the input/passthrough_data folder contents to the data folder.

feat(pipeline): add ETL for passthrough data files and folders

---

frontend/beforeStart.js
frontend/src/assets/theme.css
frontend/src/components/common/IconButton/IconButton.tsx
frontend/src/components/common/Map/Map.tsx
frontend/src/components/layout/OptionTrack/OptionButton.tsx
frontend/src/components/layout/OptionTrack/OptionTrack.tsx
frontend/src/data.d.ts
frontend/src/hooks/useAppData.ts
frontend/src/hooks/useMapData.tsx
frontend/src/utils/renderers/createBusStopRenderer.ts
frontend/src/views/RoadsVsTransit.tsx

This is the initial implementation of the data for tab 5.
- mile-based scenarios are now shown on the options track
- each mile-based scenario lets you choose between the available possibilities for the mile-based scenario
- each possibility lets to cycle through the new/changed features for that possiiblity (new stops, more benches, increased frequency, etc.)
- the map now shows all future routes, stops, and service areas in green
- the map also shows the current routes, stops, and service areas in their normal colors
Next phases will include:
- showing bench installation locations when the bench stats are shown
- highlight routes that are changed or added when a route-based stat is shown
https://github.com/user-attachments/assets/a779bb99-cc81-4580-b82b-70d58b714db8

feat(frontend): show future scenarios and routes on tab 5 (roads or transit)

---

data-pipeline/src/etl/sources/future_routes/etl.py
frontend/src/components/common/Statistic/plot/presets/hoizontalBar.ts
frontend/src/components/options/futures/SelectedFutureRoutes.tsx
frontend/src/components/options/futures/index.ts
frontend/src/components/options/index.ts
frontend/src/data.d.ts
frontend/src/hooks/useAppData.ts
frontend/src/hooks/useMapData.tsx
frontend/src/views/FutureOpportunities.tsx
frontend/src/views/GeneralAccess.tsx

Also supports comparison mode. See the screenshot below for displayed stats. The map shows the selected future route, stops, and service areas. If multiple futures are selected, all selected routes, stops, and service areas are available on the map.

feat: add map, coverage stats, work and school stats, and travel mode figure for tab 2 (future opportunities)

---

frontend/package.json
frontend/src/hooks/useAppData.ts
frontend/src/vite-env.d.ts
frontend/vite.config.ts

These are the defaults:
```
GCMD_DATA_ORIGIN=.
GCMD_DATA_PATH=/data 
```
When using the defaults, you must now run `npm run prepare` to prepare and copy the data from the data pipeline output data folder.
To avoid needing to run the data pipeline, you can specify a data location to use instead.
Example:
```
GCMD_DATA_ORIGIN=https://gis.furman.edu
GCMD_DATA_PATH=/apps/gc-mobility-dashboard/preview-gvlc/data 
```
Resolves #112

feat: support specifying a different data origin and pathname via the GCMD_DATA_ORIGIN and GCMD_DATA_PATH environment variables

---

frontend/src/components/layout/CoreFrame/CoreFrame.tsx
frontend/src/components/layout/CoreFrame/CoreFrameContext.ts
frontend/src/components/layout/PageHeader/PageHeader.tsx
frontend/src/views/EssentialServicesAccess.tsx
frontend/src/views/FutureOpportunities.tsx
frontend/src/views/GeneralAccess.tsx

This makes it easier to quickly change options when in desktop mode and the screen is not wide enough to show the sidebar in a fixed position. These new options only appear when the device is in the desktop view that is between mobile mode and fixed-sidebar mode.
Closes #136
Comparison mode disabled
Comparison mode enabled

feat(frontend): show simplified options for areas and seasons at the top of tab sections (tabs 1, 2 and 4)

---

frontend/src/components/common/ProgressRing/ProgressRing.tsx
frontend/src/components/common/index.ts
frontend/src/components/layout/CoreFrame/CoreFrame.tsx
frontend/src/hooks/useAppData.ts
frontend/src/views/EssentialServicesAccess.tsx
frontend/src/views/FutureOpportunities.tsx
frontend/src/views/GeneralAccess.tsx
frontend/src/views/JobAccess.tsx
frontend/src/views/RoadsVsTransit.tsx

These changes add a loading overlay to the tab contents when the data needed by the tab is still downloading. The overlay only appears after 500 milliseconds, so it should only be visible for users with slower connections to the data source. The loading indicator does not appear when downloading the network segments vector tiles.
Resolves #108.
Preview on 4G:
https://github.com/user-attachments/assets/bb4aed05-6d21-4e4c-948e-6b24aafec93a

feat(frontend): show loading indicators and overlay when data is downloading

---

frontend/src/components/common/Map/Map.tsx
frontend/src/hooks/useMapData.tsx

Individual layers can still be toggled in the layers manager.
Before:
After:

feat(frontend): consolidate future route layer labels in the legend

---

frontend/src/components/common/Statistic/Money.tsx
frontend/src/components/common/Statistic/Number.tsx
frontend/src/components/common/Statistic/Percent.tsx
frontend/src/components/common/Statistic/StatisticContainer.ts

- there are now borders between rows
- if row labels need multiple lines, subsequent lines are now indentend
- seasons, which used to be in parenthesis, are now below the area name with a smaller font and slightly lighter color
| Before | After |
| --- | --- |
| <img width="403" height="696" alt="image" src="https://github.com/user-attachments/assets/e248595b-665a-49fe-aa19-1fbfa41822e9" /> | <img width="402" height="640" alt="image" src="https://github.com/user-attachments/assets/a595e52d-48f2-4939-9ca1-f9705effc0d0" /> |

feat(frontend): improve statistics table clairity

---

frontend/src/components/common/Statistic/Figure.tsx
frontend/src/components/common/Statistic/Money.tsx
frontend/src/components/common/Statistic/Number.tsx
frontend/src/components/common/Statistic/Percent.tsx
frontend/src/components/common/Statistic/StatisticContainer.ts
frontend/src/views/FutureOpportunities.tsx
frontend/src/views/GeneralAccess.tsx

feat(frontend): show statistic descriptions for boardings, alightings, and trips that could use public transit

---

frontend/src/components/common/ErrorBoundary/ErrorBoundary.ts
frontend/src/components/common/Map/Map.tsx
frontend/src/components/common/Section/Section.tsx
frontend/src/components/layout/CoreFrame/CoreFrame.tsx
frontend/src/components/layout/PageHeader/PageHeader.tsx
frontend/src/views/EssentialServicesAccess.tsx
frontend/src/views/FutureOpportunities.tsx
frontend/src/views/GeneralAccess.tsx
frontend/src/views/RoadsVsTransit.tsx

- map tab shows map as label
- tab labels and content now correctly correspond to each other when there is no map
- the legend cannot be taller than the map, so the collapse button is now always visible
- the legend will not appear until the symbols are available, which prevents the current broken-looking box in the corner while it loads
- sections can declare short labels for the mobile-mode tabs, which is important when section titles are long (see tab 4)

feat(frontened): improve mobile mode usability

---

frontend/src/components/common/Statistic/plot/PlotContainer.tsx
frontend/src/components/sections/AreaDemographics.tsx
frontend/src/components/sections/RiderDemographics.tsx
frontend/src/components/sections/WorkAndSchool2.tsx

feat(frontend): hide population stats figures with a sample size less than 30 people

---

frontend/src/components/sections/WorkAndSchoolCommute.tsx

feat(frontend): wrap the commute travel method selector on tab1 in a `StatisticContainer`

---

frontend/src/assets/theme.css
frontend/src/components/layout/PageHeader/PageHeader.tsx
frontend/src/views/EssentialServicesAccess.tsx
frontend/src/views/FutureOpportunities.tsx
frontend/src/views/GeneralAccess.tsx
frontend/src/views/JobAccess.tsx
frontend/src/views/RoadsVsTransit.tsx

feat(frontend): add tab explainer text from Stephen

---

frontend/src/utils/index.ts
frontend/src/utils/map/highlightFeatures.ts
frontend/src/utils/map/zoomToLayers.ts
frontend/src/utils/requireKey.ts
frontend/src/utils/toSqlList.ts
frontend/src/views/RoadsVsTransit.tsx

The map will now zoom to highlighted routes, future routes, and stops. Additionally, if the stops layer is currently hidden, it will be temporarily unhidden when the selected scenario and scenario feature is related to bus stops.
https://github.com/user-attachments/assets/3e7f18e0-9cce-4c62-b97f-29dd7f82acd8
Additionally, the following changes were added as part of this work:
- `mapUtils.zoomToLayers` now handles the case where an extent may be `null` if the provided `query` results in no features.
- `mapUtils.zoomToLayers` now returns the result of the geometry union (`__esri.GeometryUnion`). If there were no valid extents for the union or something else went wrong, it may return `null` or `undefined`.
- `mapUtils.zoomToLayers` now accepts a null map view. In that case, it returns …

feat(frontend): zoom to highlighted features on tab 5 (roads or transit)

---

frontend/src/data.d.ts
frontend/src/hooks/useAppData.ts
frontend/src/views/RoadsVsTransit.tsx

This PR adds a new subtab to tab 5 (Roads or Transit) for listing all scenario features in a single scrollable page. As part of this change, the highlight and zoom logic was extracted into a separate function that is used by the 2 subtabs.
On mobile view, the subtabs appear the exact same way as the sections subtabs on the other 4 tabs.

feat: add subtab to tab5 for listing all scenario features in one view

---

frontend/src/components/sections/ServiceStatistics.tsx

Since the boardings and alightings counts are based on halfves of the year despite replica being based on Q2 and Q4, we now specify the month ranges.

feat(frontend): clairify the time window for boardings and alightings

---

frontend/src/hooks/useMapData.tsx

I'll work on each pop-up in a separate branch. This one is the childcare pop-up. I should have named the branch more specifically.

feat(frontend): limit childcare popup attributes to facility type, capacity, and address (Google Maps link)
